In [64]:
import pandas as pd
import numpy as np

In [65]:
file_name = None

In [66]:
# 構建一個 pd.DataFrame
data = np.arange(36).reshape(6,6)
data[0:3,0] = 1
print(data)
df = pd.DataFrame(data,columns=['A','B','C','D','E','F'])
# df
df

[[ 1  1  2  3  4  5]
 [ 1  7  8  9 10 11]
 [ 1 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


A   B   C   D   E   F
0   1   1   2   3   4   5
1   1   7   8   9  10  11
2   1  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [67]:
# 通過 pd.read_csv來獲取data
if file_name != None:
    df = pd.read_csv("document/sample_data_time_series.csv")

In [68]:
# 設定以其中一個欄位爲 index 可以直接使用 set.index
# sample_data.set_index('Time_Stamp')
# 合併重複資料思路，以給定欄位爲index，將欄位中重複的資料合併，之後再取平均
df = sample_data.groupby(by='Time_Stamp').mean()
df
# sample_data.to_csv('document/sample_data_agg.csv')

Time_Stamp_ms  CurrentCounter  TotalCounter  Current1  \
Time_Stamp                                                              
2019/4/1 09:32            0.0        1.666667  46948.666667  1.733333   
2019/4/1 09:33            0.0       10.000000  46957.500000  1.733333   
2019/4/1 09:34            0.0       22.166667  46969.500000  1.750000   
2019/4/1 09:35            0.0       34.000000  46981.500000  1.766667   
2019/4/1 09:36            0.0       46.000000  46993.333333  1.766667   
2019/4/1 09:37            0.0       57.833333  47005.333333  1.750000   
2019/4/1 09:38            0.0       69.666667  47017.166667  1.716667   
2019/4/1 09:39            0.0       81.666667  47029.000000  1.733333   
2019/4/1 09:40            0.0       93.500000  47041.166667  1.733333   
2019/4/1 09:41            0.0      105.333333  47052.666667  1.716667   
2019/4/1 09:42            0.0      117.333333  47064.833333  1.700000   
2019/4/1 09:43            0.0      129.166667  47076.500000  1.716667   
2019/4/1 09:44            0.0      140.833333  47088.333333  1.716667   
2019/4/1 09:45            0.0      152.833333  47100.333333  1.733333   
2019/4/1 09:46            0.0      164.833333  47112.333333  1.700000   
2019/4/1 09:47            0.0      176.666667  47124.166667  1.716667   
2019/4/1 09:48            0.0      188.666667  47136.166667  1.716667   
2019/4/1 09:49            0.0      200.333333  47147.833333  1.716667   
2019/4/1 09:50            0.0      212.500000  47159.833333  1.716667   
2019/4/1 09:51            0.0      221.333333  47169.000000  1.700000   
2019/4/1 09:57            0.0      262.500000  47209.500000  1.700000   
2019/4/1 09:58            0.0      307.500000  47255.000000  1.700000   
2019/4/1 09:59            0.0      319.500000  47266.833333  1.700000   
2019/4/1 10:00            0.0      331.166667  47278.500000  1.700000   
2019/4/1 10:01            0.0      343.333333  47290.666667  1.700000   
2019/4/1 10:02            0.0      355.000000  47302.333333  1.700000   
2019/4/1 10:03            0.0      366.833333  47314.333333  1.700000   
2019/4/1 10:04            0.0      378.833333  47326.166667  1.700000   
2019/4/1 10:05            0.0      390.500000  47337.833333  1.700000   
2019/4/1 10:06            0.0      399.666667  47347.166667  1.700000   
...                       ...             ...           ...       ...   
2019/4/8 10:29            0.0      520.000000  52371.833333  1.700000   
2019/4/8 10:30            0.0      535.333333  52386.666667  1.700000   
2019/4/8 10:31            0.0      550.166667  52401.833333  1.700000   
2019/4/8 10:32            0.0      564.833333  52416.333333  1.700000   
2019/4/8 10:33            0.0      580.000000  52431.500000  1.700000   
2019/4/8 10:34            0.0      594.833333  52446.166667  1.700000   
2019/4/8 10:35            0.0      609.666667  52461.000000  1.700000   
2019/4/8 10:36            0.0      624.500000  52476.000000  1.700000   
2019/4/8 10:37            0.0      639.500000  52490.833333  1.700000   
2019/4/8 10:38            0.0      654.333333  52505.666667  1.700000   
2019/4/8 10:39            0.0      669.166667  52520.833333  1.700000   
2019/4/8 10:40            0.0      684.333333  52535.666667  1.700000   
2019/4/8 10:41            0.0      698.833333  52550.500000  1.700000   
2019/4/8 10:42            0.0      714.000000  52565.500000  1.700000   
2019/4/8 10:43            0.0      729.000000  52580.166667  1.700000   
2019/4/8 10:44            0.0      743.833333  52595.166667  1.700000   
2019/4/8 10:45            0.0      758.500000  52609.833333  1.700000   
2019/4/8 10:46            0.0      773.500000  52625.000000  1.700000   
2019/4/8 10:47            0.0      788.500000  52639.833333  1.700000   
2019/4/8 10:48            0.0      803.000000  52654.500000  1.700000   
2019/4/8 10:49            0.0      818.000000  52669.500000  1.700000   
2019/4/8 10:50            0.0      833.000000  52684.333333  1.700000   
2